Adiionar préprojeto de Gilliard
UniREDENTOR/Projetos pull request #14
Opened 2018-09-05 00:52 UTC by gilliard00

2018-09-06 23:47 UTC, kelvinsouza16 commented on GilliardPacheo.md
> +A good site creation has if it investigates the key elements such as information architecture, the affordability possibility of how a project should reconcile with clarity to the end user and underst
@gilliard00 você deixou o final do parágrafo todo em inglês.

2018-09-06 23:48 UTC, elissonmichael commented on GilliardPacheo.md
> +A good site creation has if it investigates the key elements such as information architecture, the affordability possibility of how a project should reconcile with clarity to the end user and underst
Obrigado pela observação @kelvinsouza16 .

2018-09-07 23:43 UTC, elissonmichael requested changes
@gilliard00  você não pode deixar essa tradução de Google Translate. Está com problemas de concordância e o texto está com a leitura difícil e algumas partes estão sem sentido.

2018-09-07 23:43 UTC, elissonmichael commented on GilliardPacheo.md
> +Uma boa criação de site tem se investigam os principais elementos, como arquitetura da informação, a possibilidade de acessibilidade de como um projeto deve conciliar com clareza para usuário final e
@gilliard00 , você não pode deixar essa tradução de Google Translate. Está com problemas de concordância e o texto está com a leitura difícil e algumas partes estão sem sentido.

2018-09-08 22:32 UTC, gilliard00 commented
O git que traduziu em ingles

2018-09-08 22:43 UTC, gilliard00 commented
@elissonmichael
 Na verdade foi o git que colocou em inglês.
Marque para mim as partes sem sentido para que posso analisar.

2018-09-11 13:07 UTC, elissonmichael commented
@gilliard00 coloca o link do artigo/material que usou como referência para escrever aquele texto, por favor.

2018-09-17 12:51 UTC, elissonmichael approved these changes
@gilliard00, vou mesclar essas suas inclusões/alterações no repositório da Uniredentor. Qualquer atualização que você vier a fazer precisa ser nesse mesmo arquivo GilliardPacheo.md.

2018-09-17 12:51 UTC, merged