Create GabrielRibeiro.md
UniREDENTOR/Projetos pull request #36
Opened 2018-09-21 02:01 UTC by gabriel04859

Estrutura do Projeto e Artigo da APS

2018-09-23 16:51 UTC, elissonmichael requested changes
@gabriel04859, vou aguardar você atualizar as suas referências. Basta editar o seu  arquivo no repositório que fez o fork. Não precisa fazer outro pull request. Qualquer dúvida entre em contato, por favor.

2018-09-23 16:51 UTC, elissonmichael commented on GabrielRibeiro.md
> +Segundo Kishimoto (2004) a IA pode ser caracterizada de duas maneiras indiretas. Uma delas tem como foco resolver problemas complexos e aproximar o conhecimento humano em maquinas. Já a segunda denom
@gabriel04859 Você não pode citar alguém que você não incluiu nas suas Referências.

2018-09-23 16:51 UTC, elissonmichael commented on GabrielRibeiro.md
> +No campo game IA foram estabelecidas algumas regras para que a experiência se tornasse mais divertida para o usuário, para Karlsoon (2005, apud Galdino, 2007) são:
@gabriel04859 você colocou essa referência igual como ela estava no artigo original e também não incluiu elas nas referências do seu artigo.

2018-09-27 21:40 UTC, gabriel04859 commented on GabrielRibeiro.md
> +Segundo Kishimoto (2004) a IA pode ser caracterizada de duas maneiras indiretas. Uma delas tem como foco resolver problemas complexos e aproximar o conhecimento humano em maquinas. Já a segunda denom
Você poderia me dizer se agora esta tudo correto?

2018-10-04 21:37 UTC, merged

2018-10-10 17:52 UTC, elissonmichael commented
@gabriel04859, senti falta de você falando mais sobre o seu projeto. Precisa explicar um pouco mais o que pretende fazer.

Senti falta de mais duas referências de artigos que tiveram como projeto algo semelhante ou relacionado ao que vai se propor a fazer no seu projeto.﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿